import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hsviv
 */
public class LAB extends javax.swing.JFrame {
Connection con=null;
Statement st=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form LAB
     */
    public LAB() {
        initComponents();
         try {
        Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dsatm", "root", "Bdvt@1234");
            } catch (SQLException ex) {
                Logger.getLogger(LAB.class.getName()).log(Level.SEVERE, null, ex);
            }

    }  catch (ClassNotFoundException ex) {
    Logger.getLogger(LAB.class.getName()).log(Level.SEVERE, null, ex);
}
        ShowRecordINTable();
    }
    public void ShowRecordINTable(){
int c=0;
    try {
        pst=con.prepareStatement("Select * from software_lab_inventory");
        rs=pst.executeQuery();
        ResultSetMetaData rsmd=rs.getMetaData();
        c=rsmd.getColumnCount();
        DefaultTableModel DModel=(DefaultTableModel) jTable1.getModel();
                            DModel.setRowCount(0);
                            while(rs.next()){
                  Vector column =new Vector();
                  for (int i=0;i<=c;i++){
                      column.add(rs.getString("room_no"));
                      column.add(rs.getString("sl_no"));
                      column.add(rs.getString("particulars"));
                      column.add(rs.getString("dept_item_number"));
                      column.add(rs.getString("total"));
                  }
                  DModel.addRow(column);
                            }
    } catch (SQLException ex) {
        Logger.getLogger(LAB.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpart3 = new javax.swing.JTextField();
        txtdept3 = new javax.swing.JTextField();
        txtroom3 = new javax.swing.JTextField();
        txtslno3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txttotal3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "so_room_no", "so_sl_no", "so_particulars", "so_dept_item_number", "so_total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 920, 440));

        jPanel1.setBackground(new java.awt.Color(216, 239, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel1.setText("SO_ROOM_NO");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel2.setText("SO_SL_NO");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel3.setText("SO_PARTICULARS");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel4.setText("SO_DEPT_ITEM_NUMBER");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        jLabel5.setText("SO_TOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtroom3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtslno3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpart3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtdept3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtroom3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpart3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtslno3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdept3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 920, 190));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Red_X.svg (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab (2).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (txtslno3.getText().equals("") || txtroom3.getText().equals("") || txtpart3.getText().equals("") || txtdept3.getText().equals("") || txttotal3.getText().equals("")) {
    JOptionPane.showMessageDialog(this, "All Fields are Required");
    if (txtslno3.getText().equals("")) {
        txtslno3.requestFocus();
    } else if (txtroom3.getText().equals("")) {
        txtroom3.requestFocus();
    } else if (txtpart3.getText().equals("")) {
        txtpart3.requestFocus();
    } else if (txtdept3.getText().equals("")) {
        txtdept3.requestFocus();
    } else {
        txttotal3.requestFocus();
    }
} else {
    PreparedStatement pst = null;
    ResultSet rs = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dsatm", "root", "Bdvt@1234");

        // Check if the serial number already exists in the database
        pst = con.prepareStatement("select * from software_lab_inventory where room_no=? and sl_no=?");
        pst.setString(1, txtroom3.getText());
        pst.setString(2, txtslno3.getText());
        rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Item with this Serial Number already exists in the Room");
        } else {
            int price = Integer.parseInt(txttotal3.getText());

            // Insert the item into the database
            pst = con.prepareStatement("insert into software_lab_inventory(room_no, sl_no, particulars, dept_item_number, total) values(?, ?, ?, ?, ?)");
            pst.setString(1, txtroom3.getText());
            pst.setString(2, txtslno3.getText());
            pst.setString(3, txtpart3.getText());
            pst.setString(4, txtdept3.getText());
            pst.setInt(5, price);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Item Added");

            // Clear input fields after insertion
            txtroom3.setText("");
            txtslno3.setText("");
            txtpart3.setText("");
            txtdept3.setText("");
            txttotal3.setText("");

            // Refresh the table to show the updated records
            ShowRecordINTable();
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid total value: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while closing resources: " + e.getMessage());
        }
    }
}
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (txtroom3.getText().equals("") || txtslno3.getText().equals("")) {
    JOptionPane.showMessageDialog(this, "Both Room Number and Serial Number are Required");
    if (txtroom3.getText().equals("")) {
        txtroom3.requestFocus();
    } else {
        txtslno3.requestFocus();
    }
} else {
    PreparedStatement pstSelect = null;
    PreparedStatement pstDelete = null;
    ResultSet rs = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dsatm", "root", "Bdvt@1234");

        // Check if the serial number and room number combination exists in the database
        pstSelect = con.prepareStatement("select * from software_lab_inventory where room_no=? and sl_no=?");
        pstSelect.setString(1, txtroom3.getText());
        pstSelect.setString(2, txtslno3.getText());
        rs = pstSelect.executeQuery();

        if (rs.next()) {
            // Confirm before deletion
            int confirmDialog = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this item?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
            
            if (confirmDialog == JOptionPane.YES_OPTION) {
                // Perform delete operation
                pstDelete = con.prepareStatement("DELETE FROM software_lab_inventory WHERE room_no=? AND sl_no=?");
                pstDelete.setString(1, txtroom3.getText());
                pstDelete.setString(2, txtslno3.getText());
                
                int rowsDeleted = pstDelete.executeUpdate();
                
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Item Deleted Successfully");
                    // Optionally, refresh the table or UI to reflect the updated data
                    ShowRecordINTable();
                    
                    // Clear input fields after deletion
                    txtroom3.setText("");
                    txtslno3.setText("");
                    txtpart3.setText("");
                    txtdept3.setText("");
                    txttotal3.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete the item. Please try again.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No item found with the specified Room Number and Serial Number");
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pstSelect != null) pstSelect.close();
            if (pstDelete != null) pstDelete.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while closing resources: " + e.getMessage());
        }
    }
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (txtslno3.getText().equals("") || txtroom3.getText().equals("") || txtpart3.getText().equals("") || txtdept3.getText().equals("") || txttotal3.getText().equals("")) {
    JOptionPane.showMessageDialog(this, "All Fields are Required");
    if (txtslno3.getText().equals("")) {
        txtslno3.requestFocus();
    } else if (txtroom3.getText().equals("")) {
        txtroom3.requestFocus();
    } else if (txtpart3.getText().equals("")) {
        txtpart3.requestFocus();
    } else if (txtdept3.getText().equals("")) {
        txtdept3.requestFocus();
    } else {
        txttotal3.requestFocus();
    }
} else {
    PreparedStatement pst = null;
    ResultSet rs = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/dsatm", "root", "Bdvt@1234");

        pst = con.prepareStatement("select * from software_lab_inventory where sl_no=?");
        pst.setString(1, txtslno3.getText());
        rs = pst.executeQuery();

        if (!rs.next()) {
            JOptionPane.showMessageDialog(this, "Serial Number Item Does Not Exist");
        } else {
            double pric = Double.parseDouble(txttotal3.getText());

            pst = con.prepareStatement("update software_lab_inventory set room_no=?, particulars=?, dept_item_number=?, total=? where sl_no=?");
            pst.setString(1, txtroom3.getText());
            pst.setString(2, txtpart3.getText());
            pst.setString(3, txtdept3.getText());
            pst.setDouble(4, pric);
            pst.setString(5, txtslno3.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Updated");

            // Clear input fields after updating
            txtroom3.setText("");
            txtslno3.setText("");
            txtpart3.setText("");
            txtdept3.setText("");
            txttotal3.setText("");

            // Refresh the table to show the updated records
            ShowRecordINTable();
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "An error occurred: " + ex.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid total value: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred while closing resources: " + e.getMessage());
        }
    }
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtdept3;
    private javax.swing.JTextField txtpart3;
    private javax.swing.JTextField txtroom3;
    private javax.swing.JTextField txtslno3;
    private javax.swing.JTextField txttotal3;
    // End of variables declaration//GEN-END:variables
}
